In [ ]:
!pip install transformers

     |████████████████████████████████| 1.0MB 4.4MB/s 
     |████████████████████████████████| 1.1MB 20.9MB/s 
     |████████████████████████████████| 3.0MB 34.3MB/s 
     |████████████████████████████████| 890kB 46.9MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893257 sha256=5bbbd1d071cb9a35e695797d5783c1067fec49ec4b173d64d5b4c8e61ec20c5f
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
# You can include sample code which will be formatted
from transformers import AutoTokenizer,AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("rohanrajpal/bert-base-codemixed-uncased-sentiment")
model = AutoModelForSequenceClassification.from_pretrained("rohanrajpal/bert-base-codemixed-uncased-sentiment")
text = "बंदा अपना सबसे अच्छा वह"
encoded_input = tokenizer(text, return_tensors='pt')
#output = model(**encoded_input)
print(encoded_input)


{'input_ids': tensor([[   101,    887,  25501,  59878, 110334,  13432,    851,  16940, 108021,
          11208,  21547,    102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [ ]:
import pandas as pd
df=pd.read_csv("/content/final_data.csv",index_col=[0])

In [ ]:
df.columns

Index(['original', 'translated', 'Label'], dtype='object')

In [ ]:
df.head()

original  ... Label
1266  congress's coming back welcome😊😊😍😍...  ...     1
1267                   great leader with great thoughts  ...     1
1268  where the mind is without fear and the head is...  ...     1
1269  our dear adarniya rahul ji taking out poor sin...  ...     1
1270  only and only our dear adarniya educated intel...  ...     1

[5 rows x 3 columns]

In [ ]:

from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
def gen_id_mask(data):
  symptoms = data.translated.values

  # We need to add special tokens at the beginning and end of each sentence for BERT to work properly
  symptoms = ["[CLS] " + symptom + " [SEP]" for symptom in symptoms]
  labels = data.Label.values

  tokenizer = AutoTokenizer.from_pretrained("rohanrajpal/bert-base-codemixed-uncased-sentiment")

  tokenized_texts = [tokenizer.tokenize(symptom) for symptom in symptoms]
  tokenized_texts_tr=[tokenizer_text[0:256] for tokenizer_text in tokenized_texts]

  MAX_LEN = 13
  input_ids = [tokenizer.convert_tokens_to_ids(x) for x in tokenized_texts]
  input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")
  attention_masks = []

  # # Create a mask of 1s for each token followed by 0s for padding
  # for seq in input_ids:
  #   seq_mask = [float(i>0) for i in seq]
  #   attention_masks.append(seq_mask)

  print('success')
  return (input_ids,labels)

In [ ]:
in_ids,labels=gen_id_mask(df)

success


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
X=in_ids
y=labels
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2020,test_size=0.2)

clf = SGDClassifier().fit(X_train, y_train)

y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)

print("Train Accuracy is :",clf.score(X_train,y_train))
print("Classification report on train data is :\n",classification_report(y_train,y_train_pred))
print("Classification report on test data is :\n",classification_report(y_test,y_test_pred))

print("Test Accuracy is :",clf.score(X_test,y_test))
print("Confusion matrix  on train data is :\n",confusion_matrix(y_train,y_train_pred))
print("Confusion matrix on test data is :\n",confusion_matrix(y_test,y_test_pred))

Train Accuracy is : 0.5148809523809523
Classification report on train data is :
               precision    recall  f1-score   support

           0       0.40      0.04      0.08       478
           1       0.52      0.94      0.67       530

    accuracy                           0.51      1008
   macro avg       0.46      0.49      0.37      1008
weighted avg       0.46      0.51      0.39      1008

Classification report on test data is :
               precision    recall  f1-score   support

           0       0.22      0.02      0.03       114
           1       0.54      0.95      0.69       139

    accuracy                           0.53       253
   macro avg       0.38      0.48      0.36       253
weighted avg       0.40      0.53      0.39       253

Test Accuracy is : 0.5296442687747036
Confusion matrix  on train data is :
 [[ 21 457]
 [ 32 498]]
Confusion matrix on test data is :
 [[  2 112]
 [  7 132]]


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
X=in_ids
y=labels
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2020,test_size=0.2)

clf = LogisticRegression(penalty='l2').fit(X_train, y_train)

y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)

print("Train Accuracy is :",clf.score(X_train,y_train))
print("Classification report on train data is :\n",classification_report(y_train,y_train_pred))
print("Classification report on test data is :\n",classification_report(y_test,y_test_pred))

print("Test Accuracy is :",clf.score(X_test,y_test))
print("Confusion matrix  on train data is :\n",confusion_matrix(y_train,y_train_pred))
print("Confusion matrix on test data is :\n",confusion_matrix(y_test,y_test_pred))

Train Accuracy is : 0.5674603174603174
Classification report on train data is :
               precision    recall  f1-score   support

           0       0.57      0.37      0.45       478
           1       0.57      0.75      0.64       530

    accuracy                           0.57      1008
   macro avg       0.57      0.56      0.55      1008
weighted avg       0.57      0.57      0.55      1008

Classification report on test data is :
               precision    recall  f1-score   support

           0       0.42      0.27      0.33       114
           1       0.54      0.70      0.61       139

    accuracy                           0.51       253
   macro avg       0.48      0.48      0.47       253
weighted avg       0.49      0.51      0.48       253

Test Accuracy is : 0.5059288537549407
Confusion matrix  on train data is :
 [[177 301]
 [135 395]]
Confusion matrix on test data is :
 [[31 83]
 [42 97]]


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
X=in_ids
y=labels
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2020,test_size=0.2)

clf = RandomForestClassifier().fit(X_train, y_train)

y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)

print("Train Accuracy is :",clf.score(X_train,y_train))
print("Classification report on train data is :\n",classification_report(y_train,y_train_pred))
print("Classification report on test data is :\n",classification_report(y_test,y_test_pred))

print("Test Accuracy is :",clf.score(X_test,y_test))
print("Confusion matrix  on train data is :\n",confusion_matrix(y_train,y_train_pred))
print("Confusion matrix on test data is :\n",confusion_matrix(y_test,y_test_pred))

Train Accuracy is : 0.9623015873015873
Classification report on train data is :
               precision    recall  f1-score   support

           0       0.97      0.95      0.96       478
           1       0.96      0.97      0.96       530

    accuracy                           0.96      1008
   macro avg       0.96      0.96      0.96      1008
weighted avg       0.96      0.96      0.96      1008

Classification report on test data is :
               precision    recall  f1-score   support

           0       0.51      0.52      0.52       114
           1       0.60      0.60      0.60       139

    accuracy                           0.56       253
   macro avg       0.56      0.56      0.56       253
weighted avg       0.56      0.56      0.56       253

Test Accuracy is : 0.5612648221343873
Confusion matrix  on train data is :
 [[455  23]
 [ 15 515]]
Confusion matrix on test data is :
 [[59 55]
 [56 83]]


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
X=in_ids
y=labels
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2020,test_size=0.2)

clf = DecisionTreeClassifier().fit(X_train, y_train)

y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)

print("Train Accuracy is :",clf.score(X_train,y_train))
print("Classification report on train data is :\n",classification_report(y_train,y_train_pred))
print("Classification report on test data is :\n",classification_report(y_test,y_test_pred))

print("Test Accuracy is :",clf.score(X_test,y_test))
print("Confusion matrix  on train data is :\n",confusion_matrix(y_train,y_train_pred))
print("Confusion matrix on test data is :\n",confusion_matrix(y_test,y_test_pred))

Train Accuracy is : 0.9623015873015873
Classification report on train data is :
               precision    recall  f1-score   support

           0       0.94      0.98      0.96       478
           1       0.98      0.95      0.96       530

    accuracy                           0.96      1008
   macro avg       0.96      0.96      0.96      1008
weighted avg       0.96      0.96      0.96      1008

Classification report on test data is :
               precision    recall  f1-score   support

           0       0.53      0.56      0.55       114
           1       0.62      0.60      0.61       139

    accuracy                           0.58       253
   macro avg       0.58      0.58      0.58       253
weighted avg       0.58      0.58      0.58       253

Test Accuracy is : 0.5810276679841897
Confusion matrix  on train data is :
 [[469   9]
 [ 29 501]]
Confusion matrix on test data is :
 [[64 50]
 [56 83]]


#Multilingual

In [ ]:
# You can include sample code which will be formatted
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")
text = "बंदा अपना सबसे अच्छा वह"
encoded_input = tokenizer(text, return_tensors='pt')
#output = model(**encoded_input)
print(encoded_input)


{'input_ids': tensor([[   101,    887,  52768,  11208,  59878,  28603,    851, 102752,  21547,
            102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [ ]:
def gen_id_mask(data):
  symptoms = data.Translated.values

  # We need to add special tokens at the beginning and end of each sentence for BERT to work properly
  symptoms = ["[CLS] " + symptom + " [SEP]" for symptom in symptoms]
  labels = data.Label.values

  tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")

  tokenized_texts = [tokenizer.tokenize(symptom) for symptom in symptoms]
  tokenized_texts_tr=[tokenizer_text[0:256] for tokenizer_text in tokenized_texts]

  MAX_LEN = 256
  input_ids = [tokenizer.convert_tokens_to_ids(x) for x in tokenized_texts]
  input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")
  attention_masks = []

  # # Create a mask of 1s for each token followed by 0s for padding
  # for seq in input_ids:
  #   seq_mask = [float(i>0) for i in seq]
  #   attention_masks.append(seq_mask)

  print('success')
  return (input_ids,labels)

In [ ]:
in_ids_ml,labels=gen_id_mask(df)

success


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
X=in_ids_ml
y=labels
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2020,test_size=0.2)

clf = LogisticRegression().fit(X_train, y_train)

y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)

print("Train Accuracy is :",clf.score(X_train,y_train))
print("Classification report on train data is :\n",classification_report(y_train,y_train_pred))
print("Classification report on test data is :\n",classification_report(y_test,y_test_pred))

print("Test Accuracy is :",clf.score(X_test,y_test))
print("Confusion matrix  on train data is :\n",confusion_matrix(y_train,y_train_pred))
print("Confusion matrix on test data is :\n",confusion_matrix(y_test,y_test_pred))

Train Accuracy is : 0.5505962521294719
Classification report on train data is :
               precision    recall  f1-score   support

           0       0.55      0.49      0.52      1447
           1       0.55      0.61      0.58      1488

    accuracy                           0.55      2935
   macro avg       0.55      0.55      0.55      2935
weighted avg       0.55      0.55      0.55      2935

Classification report on test data is :
               precision    recall  f1-score   support

           0       0.54      0.48      0.50       364
           1       0.54      0.59      0.56       370

    accuracy                           0.54       734
   macro avg       0.54      0.53      0.53       734
weighted avg       0.54      0.54      0.53       734

Test Accuracy is : 0.5354223433242506
Confusion matrix  on train data is :
 [[712 735]
 [584 904]]
Confusion matrix on test data is :
 [[173 191]
 [150 220]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


#Hidi hindi-tpu-electra

In [ ]:
def gen_id_mask(data):
  symptoms = data.Translated.values

  # We need to add special tokens at the beginning and end of each sentence for BERT to work properly
  symptoms = ["[CLS] " + symptom + " [SEP]" for symptom in symptoms]
  labels = data.Label.values

  tokenizer = AutoTokenizer.from_pretrained("monsoon-nlp/hindi-tpu-electra")

  tokenized_texts = [tokenizer.tokenize(symptom) for symptom in symptoms]
  tokenized_texts_tr=[tokenizer_text[0:256] for tokenizer_text in tokenized_texts]

  MAX_LEN = 256
  input_ids = [tokenizer.convert_tokens_to_ids(x) for x in tokenized_texts]
  input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")
  attention_masks = []

  # # Create a mask of 1s for each token followed by 0s for padding
  # for seq in input_ids:
  #   seq_mask = [float(i>0) for i in seq]
  #   attention_masks.append(seq_mask)

  print('success')
  return (input_ids,labels)

In [ ]:
in_ids_ml1,labels=gen_id_mask(df)

success


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
X=in_ids_ml1
y=labels
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2020,test_size=0.2)

clf = LogisticRegression().fit(X_train, y_train)

y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)

print("Train Accuracy is :",clf.score(X_train,y_train))
print("Classification report on train data is :\n",classification_report(y_train,y_train_pred))
print("Classification report on test data is :\n",classification_report(y_test,y_test_pred))

print("Test Accuracy is :",clf.score(X_test,y_test))
print("Confusion matrix  on train data is :\n",confusion_matrix(y_train,y_train_pred))
print("Confusion matrix on test data is :\n",confusion_matrix(y_test,y_test_pred))

Train Accuracy is : 0.5505962521294719
Classification report on train data is :
               precision    recall  f1-score   support

           0       0.55      0.49      0.52      1447
           1       0.55      0.61      0.58      1488

    accuracy                           0.55      2935
   macro avg       0.55      0.55      0.55      2935
weighted avg       0.55      0.55      0.55      2935

Classification report on test data is :
               precision    recall  f1-score   support

           0       0.54      0.48      0.50       364
           1       0.54      0.59      0.56       370

    accuracy                           0.54       734
   macro avg       0.54      0.53      0.53       734
weighted avg       0.54      0.54      0.53       734

Test Accuracy is : 0.5354223433242506
Confusion matrix  on train data is :
 [[712 735]
 [584 904]]
Confusion matrix on test data is :
 [[173 191]
 [150 220]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


#GPT2

In [ ]:

def gen_id_mask(data):
  symptoms = data.Translated.values

  # We need to add special tokens at the beginning and end of each sentence for BERT to work properly
  symptoms = ["[CLS] " + symptom + " [SEP]" for symptom in symptoms]
  labels = data.Label.values

  tokenizer = AutoTokenizer.from_pretrained("surajp/gpt2-hindi")

  tokenized_texts = [tokenizer.tokenize(symptom) for symptom in symptoms]
  tokenized_texts_tr=[tokenizer_text[0:256] for tokenizer_text in tokenized_texts]

  MAX_LEN = 256
  input_ids = [tokenizer.convert_tokens_to_ids(x) for x in tokenized_texts]
  input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")
  attention_masks = []

  # # Create a mask of 1s for each token followed by 0s for padding
  # for seq in input_ids:
  #   seq_mask = [float(i>0) for i in seq]
  #   attention_masks.append(seq_mask)

  print('success')
  return (input_ids,labels)

In [ ]:
in_ids_ml2,labels=gen_id_mask(df)
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
X=in_ids_ml2
y=labels
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2020,test_size=0.2)

clf = LogisticRegression().fit(X_train, y_train)

y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)

print("Train Accuracy is :",clf.score(X_train,y_train))
print("Classification report on train data is :\n",classification_report(y_train,y_train_pred))
print("Classification report on test data is :\n",classification_report(y_test,y_test_pred))

print("Test Accuracy is :",clf.score(X_test,y_test))
print("Confusion matrix  on train data is :\n",confusion_matrix(y_train,y_train_pred))
print("Confusion matrix on test data is :\n",confusion_matrix(y_test,y_test_pred))

success
Train Accuracy is : 0.6078364565587734
Classification report on train data is :
               precision    recall  f1-score   support

           0       0.60      0.61      0.61      1447
           1       0.62      0.60      0.61      1488

    accuracy                           0.61      2935
   macro avg       0.61      0.61      0.61      2935
weighted avg       0.61      0.61      0.61      2935

Classification report on test data is :
               precision    recall  f1-score   support

           0       0.54      0.52      0.53       364
           1       0.54      0.56      0.55       370

    accuracy                           0.54       734
   macro avg       0.54      0.54      0.54       734
weighted avg       0.54      0.54      0.54       734

Test Accuracy is : 0.5395095367847411
Confusion matrix  on train data is :
 [[884 563]
 [588 900]]
Confusion matrix on test data is :
 [[190 174]
 [164 206]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


#ROBERTA

In [ ]:
def gen_id_mask(data):
  symptoms = data.Translated.values

  # We need to add special tokens at the beginning and end of each sentence for BERT to work properly
  symptoms = ["[CLS] " + symptom + " [SEP]" for symptom in symptoms]
  labels = data.Label.values

  tokenizer = AutoTokenizer.from_pretrained("surajp/RoBERTa-hindi-guj-san")

  tokenized_texts = [tokenizer.tokenize(symptom) for symptom in symptoms]
  tokenized_texts_tr=[tokenizer_text[0:256] for tokenizer_text in tokenized_texts]

  MAX_LEN = 256
  input_ids = [tokenizer.convert_tokens_to_ids(x) for x in tokenized_texts]
  input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", truncating="post", padding="post")
  attention_masks = []

  # # Create a mask of 1s for each token followed by 0s for padding
  # for seq in input_ids:
  #   seq_mask = [float(i>0) for i in seq]
  #   attention_masks.append(seq_mask)

  print('success')
  return (input_ids,labels)


in_ids_ml3,labels=gen_id_mask(df)
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
X=in_ids_ml3
y=labels
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2020,test_size=0.2)

clf = LogisticRegression().fit(X_train, y_train)

y_train_pred=clf.predict(X_train)
y_test_pred=clf.predict(X_test)

print("Train Accuracy is :",clf.score(X_train,y_train))
print("Classification report on train data is :\n",classification_report(y_train,y_train_pred))
print("Classification report on test data is :\n",classification_report(y_test,y_test_pred))

print("Test Accuracy is :",clf.score(X_test,y_test))
print("Confusion matrix  on train data is :\n",confusion_matrix(y_train,y_train_pred))
print("Confusion matrix on test data is :\n",confusion_matrix(y_test,y_test_pred))


success
Train Accuracy is : 0.6054514480408859
Classification report on train data is :
               precision    recall  f1-score   support

           0       0.60      0.62      0.61      1447
           1       0.61      0.59      0.60      1488

    accuracy                           0.61      2935
   macro avg       0.61      0.61      0.61      2935
weighted avg       0.61      0.61      0.61      2935

Classification report on test data is :
               precision    recall  f1-score   support

           0       0.55      0.55      0.55       364
           1       0.56      0.56      0.56       370

    accuracy                           0.56       734
   macro avg       0.56      0.56      0.56       734
weighted avg       0.56      0.56      0.56       734

Test Accuracy is : 0.555858310626703
Confusion matrix  on train data is :
 [[894 553]
 [605 883]]
Confusion matrix on test data is :
 [[199 165]
 [161 209]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
in_ids.shape
in_ids=in_ids.reshape(-1,256)

#Tensorflow.keras model

In [ ]:
import tensorflow as tf
tf.keras.backend.clear_session()
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape=(256,)))
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(16,activation='relu'))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.0001,momentum=0.9,nesterov=True), loss=tf.keras.losses.BinaryCrossentropy(),metrics=['acc'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               32896     
_________________________________________________________________
batch_normalization (BatchNo (None, 128)               512       
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8256      
_________________________________________________________________
batch_normalization_1 (Batch (None, 64)                256       
_________________________________________________________________
dense_2 (Dense)              (None, 16)                1040      
_________________________________________________________________
batch_normalization_2 (Batch (None, 16)                64        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 1

In [ ]:
hist=model.fit(in_ids,labels,validation_split=0.2,verbose=2,epochs=10)

Epoch 1/10
92/92 - 0s - loss: 0.9067 - acc: 0.5083 - val_loss: 0.7543 - val_acc: 0.5259
Epoch 2/10
92/92 - 0s - loss: 0.8447 - acc: 0.5210 - val_loss: 0.7525 - val_acc: 0.5572
Epoch 3/10
92/92 - 0s - loss: 0.7975 - acc: 0.5400 - val_loss: 0.7555 - val_acc: 0.5518
Epoch 4/10
92/92 - 0s - loss: 0.7860 - acc: 0.5353 - val_loss: 0.7583 - val_acc: 0.5599
Epoch 5/10
92/92 - 0s - loss: 0.7476 - acc: 0.5492 - val_loss: 0.7541 - val_acc: 0.5518
Epoch 6/10
92/92 - 0s - loss: 0.7470 - acc: 0.5595 - val_loss: 0.7569 - val_acc: 0.5422
Epoch 7/10
92/92 - 0s - loss: 0.7310 - acc: 0.5615 - val_loss: 0.7561 - val_acc: 0.5463
Epoch 8/10
92/92 - 0s - loss: 0.7285 - acc: 0.5537 - val_loss: 0.7375 - val_acc: 0.5409
Epoch 9/10
92/92 - 0s - loss: 0.7074 - acc: 0.5595 - val_loss: 0.7390 - val_acc: 0.5490
Epoch 10/10
92/92 - 0s - loss: 0.7035 - acc: 0.5652 - val_loss: 0.7448 - val_acc: 0.5463


In [ ]:
hist=model.fit(in_ids,labels,validation_split=0.2,verbose=2,epochs=10)

Epoch 1/10
92/92 - 0s - loss: 0.7045 - acc: 0.5673 - val_loss: 0.7460 - val_acc: 0.5436
Epoch 2/10
92/92 - 0s - loss: 0.6973 - acc: 0.5840 - val_loss: 0.7475 - val_acc: 0.5232
Epoch 3/10
92/92 - 0s - loss: 0.6902 - acc: 0.5813 - val_loss: 0.7497 - val_acc: 0.5327
Epoch 4/10
92/92 - 0s - loss: 0.6742 - acc: 0.5908 - val_loss: 0.7505 - val_acc: 0.5327
Epoch 5/10
92/92 - 0s - loss: 0.6854 - acc: 0.5911 - val_loss: 0.7511 - val_acc: 0.5327
Epoch 6/10
92/92 - 0s - loss: 0.6831 - acc: 0.5915 - val_loss: 0.7487 - val_acc: 0.5381
Epoch 7/10
92/92 - 0s - loss: 0.6717 - acc: 0.5956 - val_loss: 0.7476 - val_acc: 0.5327
Epoch 8/10
92/92 - 0s - loss: 0.6782 - acc: 0.5891 - val_loss: 0.7471 - val_acc: 0.5368
Epoch 9/10
92/92 - 0s - loss: 0.6603 - acc: 0.6126 - val_loss: 0.7479 - val_acc: 0.5313
Epoch 10/10
92/92 - 0s - loss: 0.6717 - acc: 0.5963 - val_loss: 0.7498 - val_acc: 0.5286
